server:
  port: 9051

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chetanchilhate/spring-cloud
          default-label: main
          clone-on-start: true