server:
  port: 8086
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ON_PARAM
    include-exception: false

spring:
  application:
    name: CONSTELLATION-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/spring-db
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://dc-mysql:3306/spring-db

eureka:
  client:
    service-url:
      defaultZone: http://dc-service-registry:8761/eureka/
