
INSERT INTO t_constellation (id, name) VALUES ('1', 'Andromeda')
INSERT INTO t_constellation (id, name) VALUES ('2', 'Antlia')
INSERT INTO t_constellation (id, name) VALUES ('3', 'Apus')
INSERT INTO t_constellation (id, name) VALUES ('4', 'Aquarius')
INSERT INTO t_constellation (id, name) VALUES ('5', 'Aquila')
INSERT INTO t_constellation (id, name) VALUES ('6', 'Ara')
INSERT INTO t_constellation (id, name) VALUES ('7', 'Aries')
INSERT INTO t_constellation (id, name) VALUES ('8', 'Auriga')
INSERT INTO t_constellation (id, name) VALUES ('9', 'Boötes')
INSERT INTO t_constellation (id, name) VALUES ('10', 'Caelum')
INSERT INTO t_constellation (id, name) VALUES ('11', 'Camelopardalis')
INSERT INTO t_constellation (id, name) VALUES ('12', 'Cancer')
INSERT INTO t_constellation (id, name) VALUES ('13', 'Canes Venatici')
INSERT INTO t_constellation (id, name) VALUES ('14', 'Canis Major')
INSERT INTO t_constellation (id, name) VALUES ('15', 'Canis Minor')
INSERT INTO t_constellation (id, name) VALUES ('16', 'Capricornus')
INSERT INTO t_constellation (id, name) VALUES ('17', 'Carina')
INSERT INTO t_constellation (id, name) VALUES ('18', 'Cassiopeia')
INSERT INTO t_constellation (id, name) VALUES ('19', 'Centaurus')
INSERT INTO t_constellation (id, name) VALUES ('20', 'Cepheus')
INSERT INTO t_constellation (id, name) VALUES ('21', 'Cetus')
INSERT INTO t_constellation (id, name) VALUES ('22', 'Chamaeleon')
INSERT INTO t_constellation (id, name) VALUES ('23', 'Circinus')
INSERT INTO t_constellation (id, name) VALUES ('24', 'Columba')
INSERT INTO t_constellation (id, name) VALUES ('25', 'Coma Berenices')
INSERT INTO t_constellation (id, name) VALUES ('26', 'Corona Australis')
INSERT INTO t_constellation (id, name) VALUES ('27', 'Corona Borealis')
INSERT INTO t_constellation (id, name) VALUES ('28', 'Corvus')
INSERT INTO t_constellation (id, name) VALUES ('29', 'Crater')
INSERT INTO t_constellation (id, name) VALUES ('30', 'Crux')
INSERT INTO t_constellation (id, name) VALUES ('31', 'Cygnus')
INSERT INTO t_constellation (id, name) VALUES ('32', 'Delphinus')
INSERT INTO t_constellation (id, name) VALUES ('33', 'Dorado')
INSERT INTO t_constellation (id, name) VALUES ('34', 'Draco')
INSERT INTO t_constellation (id, name) VALUES ('35', 'Equuleus')
INSERT INTO t_constellation (id, name) VALUES ('36', 'Eridanus')
INSERT INTO t_constellation (id, name) VALUES ('37', 'Fornax')
INSERT INTO t_constellation (id, name) VALUES ('38', 'Gemini')
INSERT INTO t_constellation (id, name) VALUES ('39', 'Grus')
INSERT INTO t_constellation (id, name) VALUES ('40', 'Hercules')
INSERT INTO t_constellation (id, name) VALUES ('41', 'Horologium')
INSERT INTO t_constellation (id, name) VALUES ('42', 'Hydra')
INSERT INTO t_constellation (id, name) VALUES ('43', 'Hydrus')
INSERT INTO t_constellation (id, name) VALUES ('44', 'Indus')
INSERT INTO t_constellation (id, name) VALUES ('45', 'Lacerta')
INSERT INTO t_constellation (id, name) VALUES ('46', 'Leo')
INSERT INTO t_constellation (id, name) VALUES ('47', 'Leo Minor')
INSERT INTO t_constellation (id, name) VALUES ('48', 'Lepus')
INSERT INTO t_constellation (id, name) VALUES ('49', 'Libra')
INSERT INTO t_constellation (id, name) VALUES ('50', 'Lupus')
INSERT INTO t_constellation (id, name) VALUES ('51', 'Lynx')
INSERT INTO t_constellation (id, name) VALUES ('52', 'Lyra')
INSERT INTO t_constellation (id, name) VALUES ('53', 'Mensa')
INSERT INTO t_constellation (id, name) VALUES ('54', 'Microscopium')
INSERT INTO t_constellation (id, name) VALUES ('55', 'Monoceros')
INSERT INTO t_constellation (id, name) VALUES ('56', 'Musca')
INSERT INTO t_constellation (id, name) VALUES ('57', 'Norma')
INSERT INTO t_constellation (id, name) VALUES ('58', 'Octans')
INSERT INTO t_constellation (id, name) VALUES ('59', 'Ophiuchus')
INSERT INTO t_constellation (id, name) VALUES ('60', 'Orion')
INSERT INTO t_constellation (id, name) VALUES ('61', 'Pavo')
INSERT INTO t_constellation (id, name) VALUES ('62', 'Pegasus')
INSERT INTO t_constellation (id, name) VALUES ('63', 'Perseus')
INSERT INTO t_constellation (id, name) VALUES ('64', 'Phoenix')
INSERT INTO t_constellation (id, name) VALUES ('65', 'Pictor')
INSERT INTO t_constellation (id, name) VALUES ('66', 'Pisces')
INSERT INTO t_constellation (id, name) VALUES ('67', 'Piscis Austrinus')
INSERT INTO t_constellation (id, name) VALUES ('68', 'Puppis')
INSERT INTO t_constellation (id, name) VALUES ('69', 'Pyxis')
INSERT INTO t_constellation (id, name) VALUES ('70', 'Reticulum')
INSERT INTO t_constellation (id, name) VALUES ('71', 'Sagitta')
INSERT INTO t_constellation (id, name) VALUES ('72', 'Sagittarius')
INSERT INTO t_constellation (id, name) VALUES ('73', 'Scorpius')
INSERT INTO t_constellation (id, name) VALUES ('74', 'Sculptor')
INSERT INTO t_constellation (id, name) VALUES ('75', 'Scutum')
INSERT INTO t_constellation (id, name) VALUES ('76', 'Serpens')
INSERT INTO t_constellation (id, name) VALUES ('77', 'Sextans')
INSERT INTO t_constellation (id, name) VALUES ('78', 'Taurus')
INSERT INTO t_constellation (id, name) VALUES ('79', 'Telescopium')
INSERT INTO t_constellation (id, name) VALUES ('80', 'Triangulum')
INSERT INTO t_constellation (id, name) VALUES ('81', 'Triangulum Australe')
INSERT INTO t_constellation (id, name) VALUES ('82', 'Tucana')
INSERT INTO t_constellation (id, name) VALUES ('83', 'Ursa Major')
INSERT INTO t_constellation (id, name) VALUES ('84', 'Ursa Minor')
INSERT INTO t_constellation (id, name) VALUES ('85', 'Vela')
INSERT INTO t_constellation (id, name) VALUES ('86', 'Virgo')
INSERT INTO t_constellation (id, name) VALUES ('87', 'Volans')
INSERT INTO t_constellation (id, name) VALUES ('88', 'Vulpecula')
